version: '3'
services:
  account-db:
    image: postgres_uuid
    build: pgres-extention
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - $PWD/dev/data/account_db:/var/lib/postgresql/data
  account-svc:
    build:
      context: elysian_account
      dockerfile: dev.Dockerfile
    image: elysian_account
    ports:
      - 3000:8080
    links:
      - account-db
      - sentinel
    env_file: elysian_account/.env
    volumes:
      - $PWD/elysian_account:/app
    depends_on:
      - account-db
      - sentinel
