version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  postgres:
    image: postgres_uuid
    build: pgres-extention
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - $PWD/dev/data:/var/lib/postgresql/data
  account-svc:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: elysian_account
    ports:
      - 3000:8080
    links:
      - postgres
      - redis
    environment:
      - SVC_PORT
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_NAME
      - DB_PWD
      - DB_SSLMODE
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_SECRET
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
