// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/VictorDebray/elysian_account/account"
	"github.com/jinzhu/gorm"
)

import (
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

// Injectors from container.go:

func InitAccountAPI(db *gorm.DB) account.AccountAPI {
	accountRepository := account.ProvideAccountRepostiory(db)
	accountService := account.ProvideAccountService(accountRepository)
	accountAPI := account.ProvideAccountAPI(accountService)
	return accountAPI
}
